# Generated by Django 5.0.3 on 2024-05-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='review_written',
            field=models.BooleanField(default=False),
        ),
    ]
