# Generated by Django 5.0.4 on 2024-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_content_content_type_content_product_content_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='feedimage',
            name='image',
            field=models.ImageField(default='https://placehold.co/300x200', upload_to='feed_images/'),
            preserve_default=False,
        ),
    ]
