# Generated by Django 5.0.2 on 2024-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_profile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
