# Generated by Django 5.0.4 on 2024-04-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', through='cart.CartItem', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
    ]
