# Generated by Django 5.0.4 on 2024-04-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu',
            new_name='product',
        ),
    ]
