# Generated by Django 5.0.3 on 2024-05-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('orders', '0004_orderitem_review_written'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='review_written',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.content'),
        ),
    ]
